FROM busybox:latest
COPY setup-command-script.sh /usr/local/bin
LABEL org.nrg.commands="[{\"inputs\": [], \"name\": \"setup-command\", \"command-line\": \"cp /input/* /output\", \"xnat\": [], \"image\": \"xnat/test-setup-command:latest\", \"mounts\": [], \"type\": \"docker-setup\", \"description\": \"A setup command\"}]"
